import { createClient } from "@supabase/supabase-js";

// Environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate required environment variables
if (!supabaseUrl) {
  throw new Error(
    "Missing VITE_SUPABASE_URL environment variable. Please add it to your .env.local file."
  );
}

if (!supabaseAnonKey) {
  throw new Error(
    "Missing VITE_SUPABASE_ANON_KEY environment variable. Please add it to your .env.local file."
  );
}

// Create Supabase client with proper TypeScript types
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    // Auto-refresh session when it expires
    autoRefreshToken: true,
    // Persist session in local storage
    persistSession: true,
    // Detect session from URL (for OAuth callbacks)
    detectSessionInUrl: true,
  },
  // Enable realtime subscriptions (optional, can be disabled if not needed)
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Helper function to check if user is authenticated
export const isAuthenticated = async (): Promise<boolean> => {
  const {
    data: { session },
  } = await supabase.auth.getSession();
  return !!session;
};

// Helper function to get current user
export const getCurrentUser = async () => {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user;
};

// Helper function to sign out
export const signOut = async () => {
  const { error } = await supabase.auth.signOut();
  if (error) {
    throw error;
  }
};

// Export type helpers for type-safe database queries
// These will be automatically generated by Supabase CLI in future phases
export type Database = {
  public: {
    Tables: {
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          ai_personality: "professional" | "friendly" | "stern";
          currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          ai_personality?: "professional" | "friendly" | "stern";
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          ai_personality?: "professional" | "friendly" | "stern";
          currency?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      accounts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          type: "asset" | "liability";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          type: "asset" | "liability";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          type?: "asset" | "liability";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      categories: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          type: "income" | "expense";
          is_system: boolean;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          type: "income" | "expense";
          is_system?: boolean;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          type?: "income" | "expense";
          is_system?: boolean;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      subcategories: {
        Row: {
          id: string;
          user_id: string;
          category_id: string;
          name: string;
          is_system: boolean;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_id: string;
          name: string;
          is_system?: boolean;
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          category_id?: string;
          name?: string;
          is_system?: boolean;
          created_at?: string;
          deleted_at?: string | null;
        };
      };
      transactions: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          date: string;
          name: string;
          amount: number;
          subcategory_id: string | null;
          comment: string | null;
          is_initial_balance: boolean;
          ai_suggested: boolean;
          user_corrected: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          date: string;
          name: string;
          amount: number;
          subcategory_id?: string | null;
          comment?: string | null;
          is_initial_balance?: boolean;
          ai_suggested?: boolean;
          user_corrected?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          account_id?: string;
          date?: string;
          name?: string;
          amount?: number;
          subcategory_id?: string | null;
          comment?: string | null;
          is_initial_balance?: boolean;
          ai_suggested?: boolean;
          user_corrected?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      spending_goals: {
        Row: {
          id: string;
          user_id: string;
          subcategory_id: string;
          amount: number;
          period: "weekly" | "monthly" | "quarterly" | "annual";
          start_date: string;
          end_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subcategory_id: string;
          amount: number;
          period: "weekly" | "monthly" | "quarterly" | "annual";
          start_date: string;
          end_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subcategory_id?: string;
          amount?: number;
          period?: "weekly" | "monthly" | "quarterly" | "annual";
          start_date?: string;
          end_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ai_corrections: {
        Row: {
          id: string;
          user_id: string;
          transaction_name: string;
          account_id: string;
          ai_suggested_subcategory_id: string | null;
          user_corrected_subcategory_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          transaction_name: string;
          account_id: string;
          ai_suggested_subcategory_id?: string | null;
          user_corrected_subcategory_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          transaction_name?: string;
          account_id?: string;
          ai_suggested_subcategory_id?: string | null;
          user_corrected_subcategory_id?: string;
          created_at?: string;
        };
      };
      chat_sessions: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          created_at: string;
          updated_at: string;
          last_message_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          created_at?: string;
          updated_at?: string;
          last_message_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          created_at?: string;
          updated_at?: string;
          last_message_at?: string;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          role: "user" | "assistant";
          content: string;
          function_calls: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          role: "user" | "assistant";
          content: string;
          function_calls?: Record<string, unknown> | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string;
          role?: "user" | "assistant";
          content?: string;
          function_calls?: Record<string, unknown> | null;
          created_at?: string;
        };
      };
    };
  };
};
